name: I can't help but love her.
server_recipients:
  - admin@localhost
server_sender: system@localhost
frontpage_path: /frontpage

metadata:
  content_type: utf8
  content_language: en
  keywords: []
  description: 
  copyright: 
  author: 
  publisher: 
