--- 
server_recipients: 
- admin@localhost
name: ego praesto ei meus animus
frontpage_name: /frontpage
metadata:
  author: ""
  language: en
  publisher: ""
  charset: utf8
  copyright: ""
  description: ""
  keywords: ""
server_sender: system@localhost
